UPDATE pedido
SET status_pedido = CASE
    WHEN status_pedido IS NULL OR BTRIM(status_pedido) = '' THEN 'EM ANDAMENTO'
    WHEN UPPER(BTRIM(status_pedido)) IN ('EM ANDAMENTO', 'CANCELADO', 'CONCLUÍDO') THEN UPPER(BTRIM(status_pedido))
    WHEN UPPER(BTRIM(status_pedido)) IN ('PENDENTE', 'ENVIADO', 'EM PROCESSO', 'PROCESSANDO', 'PROCESSAMENTO') THEN 'EM ANDAMENTO'
    WHEN UPPER(BTRIM(status_pedido)) IN ('ENTREGUE', 'CONCLUIDO', 'CONCLUÍDO', 'FINALIZADO') THEN 'CONCLUÍDO'
    WHEN UPPER(BTRIM(status_pedido)) IN ('CANCELADO', 'CANCELO', 'CANCELADA', 'REEMBOLSADO', 'REEMBOLSADA') THEN 'CANCELADO'
    ELSE 'EM ANDAMENTO'
END
WHERE status_pedido IS DISTINCT FROM CASE
    WHEN status_pedido IS NULL OR BTRIM(status_pedido) = '' THEN 'EM ANDAMENTO'
    WHEN UPPER(BTRIM(status_pedido)) IN ('EM ANDAMENTO', 'CANCELADO', 'CONCLUÍDO') THEN UPPER(BTRIM(status_pedido))
    WHEN UPPER(BTRIM(status_pedido)) IN ('PENDENTE', 'ENVIADO', 'EM PROCESSO', 'PROCESSANDO', 'PROCESSAMENTO') THEN 'EM ANDAMENTO'
    WHEN UPPER(BTRIM(status_pedido)) IN ('ENTREGUE', 'CONCLUIDO', 'CONCLUÍDO', 'FINALIZADO') THEN 'CONCLUÍDO'
    WHEN UPPER(BTRIM(status_pedido)) IN ('CANCELADO', 'CANCELO', 'CANCELADA', 'REEMBOLSADO', 'REEMBOLSADA') THEN 'CANCELADO'
    ELSE 'EM ANDAMENTO'
END;