UPDATE pedido
SET status_pagamento = CASE
    WHEN status_pagamento IS NULL OR BTRIM(status_pagamento) = '' THEN 'EM PROCESSAMENTO'
    WHEN UPPER(BTRIM(status_pagamento)) IN ('PROCESSADO', 'EM PROCESSAMENTO', 'CANCELADO', 'NEGADO') THEN UPPER(BTRIM(status_pagamento))
    WHEN UPPER(BTRIM(status_pagamento)) IN ('PIX', 'BOLETO', 'DINHEIRO', 'CARTAO DE CREDITO', 'CARTÃO DE CRÉDITO', 'CARTAO', 'CARTÃO', 'PENDENTE', 'EM ANALISE', 'EM ANÁLISE', 'PROCESSANDO', 'EM PROCESSO') THEN 'EM PROCESSAMENTO'
    WHEN UPPER(BTRIM(status_pagamento)) IN ('APROVADO', 'PAGO', 'CONFIRMADO') THEN 'PROCESSADO'
    WHEN UPPER(BTRIM(status_pagamento)) IN ('RECUSADO', 'NEGADO', 'FALHOU', 'FALHA') THEN 'NEGADO'
    WHEN UPPER(BTRIM(status_pagamento)) IN ('CANCELADO', 'CANCELADA', 'ESTORNADO', 'ESTORNADA', 'REEMBOLSADO', 'REEMBOLSADA') THEN 'CANCELADO'
    ELSE 'EM PROCESSAMENTO'
END
WHERE status_pagamento IS DISTINCT FROM CASE
    WHEN status_pagamento IS NULL OR BTRIM(status_pagamento) = '' THEN 'EM PROCESSAMENTO'
    WHEN UPPER(BTRIM(status_pagamento)) IN ('PROCESSADO', 'EM PROCESSAMENTO', 'CANCELADO', 'NEGADO') THEN UPPER(BTRIM(status_pagamento))
    WHEN UPPER(BTRIM(status_pagamento)) IN ('PIX', 'BOLETO', 'DINHEIRO', 'CARTAO DE CREDITO', 'CARTÃO DE CRÉDITO', 'CARTAO', 'CARTÃO', 'PENDENTE', 'EM ANALISE', 'EM ANÁLISE', 'PROCESSANDO', 'EM PROCESSO') THEN 'EM PROCESSAMENTO'
    WHEN UPPER(BTRIM(status_pagamento)) IN ('APROVADO', 'PAGO', 'CONFIRMADO') THEN 'PROCESSADO'
    WHEN UPPER(BTRIM(status_pagamento)) IN ('RECUSADO', 'NEGADO', 'FALHOU', 'FALHA') THEN 'NEGADO'
    WHEN UPPER(BTRIM(status_pagamento)) IN ('CANCELADO', 'CANCELADA', 'ESTORNADO', 'ESTORNADA', 'REEMBOLSADO', 'REEMBOLSADA') THEN 'CANCELADO'
    ELSE 'EM PROCESSAMENTO'
END;