spring.application.name=justock-api


spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.zvieffvszficsiampiuo
spring.datasource.password=nsXy1jXBkAUcUo8z
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true



spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

mercadolivre.client.id=5764442794103548
mercadolivre.client.secret=kbz5L1QD6VeEcR3p3mX5zyObDRRZojap
mercadolivre.redirect.uri=https://monsoon-agent-salary.ngrok-free.dev/api/mercadolivre/callback
mercadolivre.frontend.redirect-uri=http://localhost:5173/conexoes
mercadolivre.auto-sync.enabled=true
mercadolivre.auto-sync.fixed-delay-ms=900000
mercadolivre.auto-sync.initial-delay-ms=120000